### ISSUE TITLE
this is not an "unblockable" or "completely client-side" proxy

### ISSUE THREAD

**Issue by thonkinator** [dinguschan-owo/Helios#18]
you literally just fetch to `https://corsproxy.io`, which is a server. it is 100% blockable by simple blocking `https://corsproxy.io`. it's also _less_ secure than many of TitaniumNetwork's proxies which use Wisp as the transport protocol, as Wisp allows for fully encrypted HTTPS traffic. holyyy yap bro you have no idea what you're talking about

**Comment by ProgrammerIn-wonderland** [comment]
Calm down, but yeah PSM is right

Corsproxy.io can see all of the data routed through Helios, while TN proxies which have all moved towards wisp are encrypted from client to end server by TLS and transport through a TCP proxy instead of a cors proxy, allowing the transmission of data to be fully private. The readme is misleading suggesting Helios is more private than TN proxies when it is actually much less private than modern post-wisp TN proxies.

**Comment by ProgrammerIn-wonderland** [comment]
If a sysadmin blocks the origins at
        `https://corsproxy.io/?${encodeURIComponent(url)}`,
        `https://api.codetabs.com/v1/proxy?quest=${encodeURIComponent(url)}`,
        `https://api.codetabs.com/v1/tmp/?quest=${encodeURIComponent(url)}`,
        `https://api.allorigins.win/raw?url=${encodeURIComponent(url)}`

Helios will be completely blocked and unable to function

**Comment by dinguschan-owo** [comment]
Pretty sure we went over this

**Comment by ProgrammerIn-wonderland** [comment]
Where?

**Comment by Uniolo1** [comment]
> Pretty sure we went over this

You didn't respond to it though, you just closed it. also sorry for Necro.

**Comment by dinguschan-owo** [comment]
> Where?

oh gosh @ProgrammerIn-wonderland Im so sorry i thought u were the other dude in issue #12, and you are completely right. i did update Helio's marketing, and added soem basic encryption and stuff for the reasons listed above
