### ISSUE TITLE
Weird � symbol on pages

### ISSUE THREAD

**Issue by code-leech** [dinguschan-owo/Helios#3]
When I open any page it gives � symbol

Please just don't scream at me for saying something obvious ;)

**Comment by dinguschan-owo** [comment]
ahahaha dont worry im not a dick, but the issue ur seeing is caused by the CORS header proxy im using to identify users as humans, not bots. The proxy is hosted in Paris, so when it sends the src code back some of the French symbols dont carry over, and vice versa for some english symbols. just wanted to let you know im aware and ill try and fix it.

**Comment by dinguschan-owo** [comment]
ok the symbol your seeing is U+FFFD (�) which is the unicode replacement character. There is no way to recover the original because whatever was there originally was not recognized by some system along the way to getting to you. a computer or program along the way couldn't deal with it and replaced the original text with a replacment, so the oringla can not be recovered. sorry dude :(. I'll try and auto translate from french for you and that might fix some, but its hard to tell if it will
